#ifndef VYSOKOV_VLADIMIR_RIS_25_2B_LABS_PSTU_CS_ERRORS_H
#define VYSOKOV_VLADIMIR_RIS_25_2B_LABS_PSTU_CS_ERRORS_H

enum errors {
    notFound = -2,
    outOfRange,
    ok
};

#endif //VYSOKOV_VLADIMIR_RIS_25_2B_LABS_PSTU_CS_ERRORS_H